#!/usr/bin/env bash
# ArbClaw daily update — pulls stats from arbclaw.db, generates report, commits + pushes
set -euo pipefail

ARBCLAW_DIR="$HOME/arbclaw"
DB="$ARBCLAW_DIR/arbclaw.db"
TODAY=$(date -u +%Y-%m-%d)
REPORT="$ARBCLAW_DIR/daily/$TODAY.md"
EXPERIMENT_START="2026-03-24"

# ── Calculate experiment day ──
start_epoch=$(date -j -f "%Y-%m-%d" "$EXPERIMENT_START" +%s 2>/dev/null || date -d "$EXPERIMENT_START" +%s)
today_epoch=$(date -u +%s)
day_num=$(( (today_epoch - start_epoch) / 86400 + 1 ))

# ── Query DB for stats ──
balance=$(sqlite3 "$DB" "SELECT COALESCE(balance, 1000.0) FROM daily_pnl WHERE date='$TODAY' LIMIT 1;" 2>/dev/null || echo "1000.00")
total_pnl=$(sqlite3 "$DB" "SELECT COALESCE(total_pnl, 0) FROM daily_pnl WHERE date='$TODAY' LIMIT 1;" 2>/dev/null || echo "0.00")
win_count=$(sqlite3 "$DB" "SELECT COALESCE(win_count, 0) FROM daily_pnl WHERE date='$TODAY' LIMIT 1;" 2>/dev/null || echo "0")
loss_count=$(sqlite3 "$DB" "SELECT COALESCE(loss_count, 0) FROM daily_pnl WHERE date='$TODAY' LIMIT 1;" 2>/dev/null || echo "0")
avg_latency=$(sqlite3 "$DB" "SELECT COALESCE(ROUND(avg_latency_ms, 1), 0) FROM daily_pnl WHERE date='$TODAY' LIMIT 1;" 2>/dev/null || echo "0")
ecr=$(sqlite3 "$DB" "SELECT COALESCE(ROUND(edge_capture_rate, 4), 0) FROM daily_pnl WHERE date='$TODAY' LIMIT 1;" 2>/dev/null || echo "0")

open_positions=$(sqlite3 "$DB" "SELECT COUNT(*) FROM positions WHERE status='open';" 2>/dev/null || echo "0")
total_trades=$(sqlite3 "$DB" "SELECT COUNT(*) FROM trades;" 2>/dev/null || echo "0")
total_snapshots=$(sqlite3 "$DB" "SELECT COUNT(*) FROM market_snapshots WHERE fetched_at LIKE '$TODAY%';" 2>/dev/null || echo "0")
total_signals_today=$(sqlite3 "$DB" "SELECT COUNT(*) FROM positions WHERE opened_at LIKE '$TODAY%';" 2>/dev/null || echo "0")

# Win rate
total_closed=$((win_count + loss_count))
if [ "$total_closed" -gt 0 ]; then
    win_rate=$(echo "scale=1; $win_count * 100 / $total_closed" | bc)
else
    win_rate="N/A"
fi

# ROI
roi=$(echo "scale=2; $total_pnl * 100 / 1000" | bc 2>/dev/null || echo "0.00")

# Runs today from runs.log
runs_today=$(grep -c "$TODAY" "$ARBCLAW_DIR/runs.log" 2>/dev/null || echo "0")

# ── Recent trades ──
recent_trades=$(sqlite3 -header -column "$DB" "
    SELECT market_id, direction, ROUND(entry_price, 3) as entry,
           ROUND(exit_price, 3) as exit, ROUND(pnl, 2) as pnl,
           ROUND(signal_to_trade_latency_ms, 0) as latency_ms
    FROM trades ORDER BY closed_at DESC LIMIT 5;
" 2>/dev/null || echo "(none)")

# ── Open positions ──
open_pos=$(sqlite3 -header -column "$DB" "
    SELECT market_id, direction, ROUND(entry_price, 3) as entry,
           ROUND(current_price, 3) as current, ROUND(amount_usd, 2) as size,
           ROUND(signal_to_trade_latency_ms, 0) as latency_ms
    FROM positions WHERE status='open' ORDER BY opened_at DESC LIMIT 10;
" 2>/dev/null || echo "(none)")

# ── Generate report ──
cat > "$REPORT" <<REPORT
# ArbClaw Daily Report -- $TODAY (Day $day_num/14)

## Performance Summary

| Metric | Value |
|--------|-------|
| Balance | \$$balance |
| Total PnL | \$$total_pnl |
| ROI | ${roi}% |
| Win Rate | ${win_rate}% ($win_count W / $loss_count L) |
| Avg Latency | ${avg_latency}ms |
| Edge Capture Rate | $ecr |
| Open Positions | $open_positions |
| Total Trades (all time) | $total_trades |

## Today's Activity

- Cron runs: $runs_today
- Markets scanned: $total_snapshots snapshots
- New signals: $total_signals_today
- Positions closed: $loss_count + $win_count

## Recent Trades

\`\`\`
$recent_trades
\`\`\`

## Open Positions

\`\`\`
$open_pos
\`\`\`

## Key Metric: Signal-to-Trade Latency

Target: <30 seconds. Clawmpson baseline: ~30-minute cycle.
Current avg: ${avg_latency}ms

---
*Auto-generated by ArbClaw daily-update.sh*
REPORT

echo "[arbclaw/daily] Report written: $REPORT"

# ── Commit and push ──
cd "$ARBCLAW_DIR"
git add daily/
git commit -m "$(cat <<EOF
daily report $TODAY — day $day_num | bal=\$$balance pnl=\$$total_pnl trades=$total_trades

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>
EOF
)" 2>/dev/null || echo "[arbclaw/daily] No changes to commit"

git push origin main 2>/dev/null || echo "[arbclaw/daily] Push failed — will retry next run"

echo "[arbclaw/daily] Done."
